FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*"}

[Project]
Name = "BeefCon"
TargetType = "BeefGUIApplication"
StartupObject = "BeefCon.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)\\..\\..\\IDE\\dist"
TargetName = "$(ProjectName)_d"
BeefLibType = "DynamicDebug"
DebugCommandArguments = "123 1 Powershell"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)\\..\\..\\IDE\\dist"
DebugCommandArguments = "123 1 Powershell"

[[ProjectFolder.Items]]
Type = "Source"
Path = "../../IDE/src/util/ConsoleProvider.bf"
